# Generated by Django 5.2.8 on 2026-06-11 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0006_oauthcode_pkce'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthcode',
            name='resource',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='oauthtoken',
            name='resource',
            field=models.TextField(blank=True, default=''),
        ),
    ]
